import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import IntroReveal from "@/components/IntroReveal";
import SmoothScroll from "@/components/SmoothScroll";

const ppmori = localfont({
  src: [
    {
      path: "./fonts/PPMori-Extralight.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/PPMori-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/PPMori-SemiBold.woff2",
      weight: "600",
      style: "normal",
    }
  ],
  variable: "--font-ppmori",
})

export const metadata: Metadata = {
  title: "Clov",
  description: "Generated by create next app",
  icons: {
    icon: "/faviconclov.svg",
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${ppmori.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <IntroReveal />
        <Header />
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
